### ISSUE TITLE
为什么把波特率设置为9600以上就不能工作了？

### ISSUE THREAD

**Issue by how0723** [hepingood/ch9121#9]
### Please ask your question

为什么把波特率设置为9600以上就不能工作了？

**Comment by how0723** [comment]
尝试设置更高的波特率，结果芯片再也不能工作了
![image](https://github.com/user-attachments/assets/e52b9ec3-b138-4d66-af76-b27efdcf6faf)

**Comment by how0723** [comment]
上电前拉低59脚，上电3秒，再下电，可恢复出厂设置

**Comment by how0723** [comment]
![image](https://github.com/user-attachments/assets/600f814c-6693-4dfd-ba8a-a5ed3d157089)
用配置工具也能恢复出厂设置，但是无论如何设置9600以上的波特率，都不能正常通信。9600以下的波特率没有测试

**Comment by how0723** [comment]
![image](https://github.com/user-attachments/assets/c900c778-061d-4ddd-a3b7-22223118a1d1)
 除了9600波特率测试成功，其他的波特率都不能通信成功

**Comment by libdriver** [comment]
![f8c048f94d6619c2ea8925a1562bd43](https://github.com/user-attachments/assets/3a454979-4424-4fd3-9e98-6a9cf0769995)
感谢您使用LibDriver，本驱动使用CFG0区分命令和数据，根据配置手册，配置时波特率固定为9600，当您修改配置时需要将波特率设置为9600。您也可以参考《CH9121 串口控制指令集》(/datasheet/ch9121_command.pdf)概述中第二节，配合上位机使用自动波特率。
